// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/malformed-c/periapsis/internal/server (interfaces: blobProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/test/mocks/mock_gambit.go -package=mocks github.com/malformed-c/periapsis/internal/server blobProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockblobProvider is a mock of blobProvider interface.
type MockblobProvider struct {
	ctrl     *gomock.Controller
	recorder *MockblobProviderMockRecorder
	isgomock struct{}
}

// MockblobProviderMockRecorder is the mock recorder for MockblobProvider.
type MockblobProviderMockRecorder struct {
	mock *MockblobProvider
}

// NewMockblobProvider creates a new mock instance.
func NewMockblobProvider(ctrl *gomock.Controller) *MockblobProvider {
	mock := &MockblobProvider{ctrl: ctrl}
	mock.recorder = &MockblobProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockblobProvider) EXPECT() *MockblobProviderMockRecorder {
	return m.recorder
}

// BlobPath mocks base method.
func (m *MockblobProvider) BlobPath(hash string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobPath", hash)
	ret0, _ := ret[0].(string)
	return ret0
}

// BlobPath indicates an expected call of BlobPath.
func (mr *MockblobProviderMockRecorder) BlobPath(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobPath", reflect.TypeOf((*MockblobProvider)(nil).BlobPath), hash)
}
