// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/listers/core/v1 (interfaces: ConfigMapLister,SecretLister,ConfigMapNamespaceLister,SecretNamespaceLister)
//
// Generated by this command:
//
//	mockgen -destination=internal/test/mocks/mock_listers.go -package=mocks k8s.io/client-go/listers/core/v1 ConfigMapLister,SecretLister,ConfigMapNamespaceLister,SecretNamespaceLister
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	v10 "k8s.io/client-go/listers/core/v1"
)

// MockConfigMapLister is a mock of ConfigMapLister interface.
type MockConfigMapLister struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMapListerMockRecorder
	isgomock struct{}
}

// MockConfigMapListerMockRecorder is the mock recorder for MockConfigMapLister.
type MockConfigMapListerMockRecorder struct {
	mock *MockConfigMapLister
}

// NewMockConfigMapLister creates a new mock instance.
func NewMockConfigMapLister(ctrl *gomock.Controller) *MockConfigMapLister {
	mock := &MockConfigMapLister{ctrl: ctrl}
	mock.recorder = &MockConfigMapListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigMapLister) EXPECT() *MockConfigMapListerMockRecorder {
	return m.recorder
}

// ConfigMaps mocks base method.
func (m *MockConfigMapLister) ConfigMaps(namespace string) v10.ConfigMapNamespaceLister {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigMaps", namespace)
	ret0, _ := ret[0].(v10.ConfigMapNamespaceLister)
	return ret0
}

// ConfigMaps indicates an expected call of ConfigMaps.
func (mr *MockConfigMapListerMockRecorder) ConfigMaps(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigMaps", reflect.TypeOf((*MockConfigMapLister)(nil).ConfigMaps), namespace)
}

// List mocks base method.
func (m *MockConfigMapLister) List(selector labels.Selector) ([]*v1.ConfigMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", selector)
	ret0, _ := ret[0].([]*v1.ConfigMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConfigMapListerMockRecorder) List(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConfigMapLister)(nil).List), selector)
}

// MockSecretLister is a mock of SecretLister interface.
type MockSecretLister struct {
	ctrl     *gomock.Controller
	recorder *MockSecretListerMockRecorder
	isgomock struct{}
}

// MockSecretListerMockRecorder is the mock recorder for MockSecretLister.
type MockSecretListerMockRecorder struct {
	mock *MockSecretLister
}

// NewMockSecretLister creates a new mock instance.
func NewMockSecretLister(ctrl *gomock.Controller) *MockSecretLister {
	mock := &MockSecretLister{ctrl: ctrl}
	mock.recorder = &MockSecretListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretLister) EXPECT() *MockSecretListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSecretLister) List(selector labels.Selector) ([]*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", selector)
	ret0, _ := ret[0].([]*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretListerMockRecorder) List(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretLister)(nil).List), selector)
}

// Secrets mocks base method.
func (m *MockSecretLister) Secrets(namespace string) v10.SecretNamespaceLister {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secrets", namespace)
	ret0, _ := ret[0].(v10.SecretNamespaceLister)
	return ret0
}

// Secrets indicates an expected call of Secrets.
func (mr *MockSecretListerMockRecorder) Secrets(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secrets", reflect.TypeOf((*MockSecretLister)(nil).Secrets), namespace)
}

// MockConfigMapNamespaceLister is a mock of ConfigMapNamespaceLister interface.
type MockConfigMapNamespaceLister struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMapNamespaceListerMockRecorder
	isgomock struct{}
}

// MockConfigMapNamespaceListerMockRecorder is the mock recorder for MockConfigMapNamespaceLister.
type MockConfigMapNamespaceListerMockRecorder struct {
	mock *MockConfigMapNamespaceLister
}

// NewMockConfigMapNamespaceLister creates a new mock instance.
func NewMockConfigMapNamespaceLister(ctrl *gomock.Controller) *MockConfigMapNamespaceLister {
	mock := &MockConfigMapNamespaceLister{ctrl: ctrl}
	mock.recorder = &MockConfigMapNamespaceListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigMapNamespaceLister) EXPECT() *MockConfigMapNamespaceListerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigMapNamespaceLister) Get(name string) (*v1.ConfigMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(*v1.ConfigMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigMapNamespaceListerMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigMapNamespaceLister)(nil).Get), name)
}

// List mocks base method.
func (m *MockConfigMapNamespaceLister) List(selector labels.Selector) ([]*v1.ConfigMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", selector)
	ret0, _ := ret[0].([]*v1.ConfigMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConfigMapNamespaceListerMockRecorder) List(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConfigMapNamespaceLister)(nil).List), selector)
}

// MockSecretNamespaceLister is a mock of SecretNamespaceLister interface.
type MockSecretNamespaceLister struct {
	ctrl     *gomock.Controller
	recorder *MockSecretNamespaceListerMockRecorder
	isgomock struct{}
}

// MockSecretNamespaceListerMockRecorder is the mock recorder for MockSecretNamespaceLister.
type MockSecretNamespaceListerMockRecorder struct {
	mock *MockSecretNamespaceLister
}

// NewMockSecretNamespaceLister creates a new mock instance.
func NewMockSecretNamespaceLister(ctrl *gomock.Controller) *MockSecretNamespaceLister {
	mock := &MockSecretNamespaceLister{ctrl: ctrl}
	mock.recorder = &MockSecretNamespaceListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretNamespaceLister) EXPECT() *MockSecretNamespaceListerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSecretNamespaceLister) Get(name string) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecretNamespaceListerMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSecretNamespaceLister)(nil).Get), name)
}

// List mocks base method.
func (m *MockSecretNamespaceLister) List(selector labels.Selector) ([]*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", selector)
	ret0, _ := ret[0].([]*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretNamespaceListerMockRecorder) List(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretNamespaceLister)(nil).List), selector)
}
