// Copyright (C) 2025-2026 Malformed C. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

package join

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// defaultConfigTemplate is the perigeos.toml generated on join.
//
// When primary=true the config processor auto-generates a pawn named after
// os.Hostname() - no explicit [pawns.*] section is needed or allowed
// (it would collide). The primary pawn represents the physical host node.
//
// When primary=false (kubelet already owns the host) we add one explicit
// pawn named {hostname}-01 so perigeos has something to run.
const defaultConfigTemplate = `# perigeos.toml - generated by 'perigeos join'
# Edit this file to add more pawns or tune resource limits.
# Apply changes by restarting: systemctl restart perigeos

[global]
# Base port - primary pawn uses this port; extra pawns get PerigeosPort+N.
PerigeosPort = 12260

DefaultCPU    = "100%"
DefaultMemory = "512M"

# primary=true: perigeos registers the physical host ({{.Hostname}}) as a
# cluster node. Use false when a kubelet (k3s/kubeadm) already owns this host.
primary = {{.Primary}}

{{if .ConstellationCNI -}}
# Constellation CNI detected in the cluster and enabled automatically.
# Cross-host pod connectivity requires the constellation-agent DaemonSet.
[global.cni]
# bin_dir  = "/opt/cni/bin"
# conf_dir = "/etc/cni/net.d/constellation"
# debug    = false
{{- else -}}
# Constellation CNI was not detected. If you deploy it later, uncomment
# [global.cni] to enable cross-host pod connectivity.
# [global.cni]
# bin_dir  = "/opt/cni/bin"
# conf_dir = "/etc/cni/net.d/constellation"
# debug    = false
{{- end}}
{{if not .Primary}}
# primary=false: kubelet already registered {{.Hostname}}, so perigeos runs
# as a sidecar. Add more [pawns.*] sections to scale up.
[pawns.{{.PawnName}}]
cpu    = "100%"
memory = "512M"

[pawns.{{.PawnName}}.labels]
"kubernetes.io/os"   = "linux"
"kubernetes.io/arch" = "amd64"

[pawns.{{.PawnName}}.taints]
"node.periapsis.io/type" = "pawn:NoSchedule"
{{end}}`

// generateConfig writes a default perigeos.toml to {configDir}/perigeos.toml.
// If the file already exists it is left unchanged to preserve user edits.
func generateConfig(opts *Options, primary, constellationCNI bool, logger *slog.Logger) (string, error) {
	configPath := filepath.Join(opts.ConfigDir, "perigeos.toml")

	if _, err := os.Stat(configPath); err == nil {
		logger.Info("Config already exists - skipping generation", "path", configPath)
		return configPath, nil
	}

	hostname, err := os.Hostname()
	if err != nil || hostname == "" {
		hostname = "node"
	}
	safeHost := sanitizePawnName(hostname)
	// Non-primary pawn name: hostname-01 (distinct from any primary node name).
	pawnName := safeHost + "-01"

	tmpl, err := template.New("config").
		Funcs(template.FuncMap{"not": func(b bool) bool { return !b }}).
		Parse(defaultConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("parse config template: %w", err)
	}

	data := struct {
		Primary          bool
		Hostname         string
		PawnName         string
		ConstellationCNI bool
	}{
		Primary:          primary,
		Hostname:         hostname,
		PawnName:         pawnName,
		ConstellationCNI: constellationCNI,
	}

	f, err := os.OpenFile(configPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o640)
	if err != nil {
		return "", fmt.Errorf("create config file %s: %w", configPath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("render config template: %w", err)
	}

	if primary {
		logger.Info("Default config written", "path", configPath, "primary_node", hostname, "primary", true)
	} else {
		logger.Info("Default config written", "path", configPath, "pawn", pawnName, "primary", false)
	}
	return configPath, nil
}

// sanitizePawnName converts a hostname into a valid pawn name.
// It lowercases, replaces underscores/dots with hyphens, and trims.
func sanitizePawnName(name string) string {
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, "_", "-")
	name = strings.ReplaceAll(name, ".", "-")
	name = strings.Trim(name, "-")
	if name == "" {
		return "pawn-01"
	}
	return name
}
