package join

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// defaultConfigTemplate is the perigeos.toml generated on join.
// It starts with 1 pawn and primary auto-detected from kubelet scan.
const defaultConfigTemplate = `# perigeos.toml — generated by 'perigeos join'
# Edit this file to add more pawns or tune resource limits.
# Apply changes by restarting: systemctl restart perigeos

[global]
# Base port — pawns get ports starting from PerigeosPort+1.
PerigeosPort = 12260

DefaultCPU    = "100%"
DefaultMemory = "512M"

# primary=true registers the physical host as a node in the cluster.
# Set to false if a kubelet (k3s/kubeadm) already owns this host.
primary = {{.Primary}}

# Constellation CNI is auto-detected via /var/run/cilium/cilium.sock.
# Uncomment and configure to pin the settings explicitly.
# [global.cni]
# bin_dir  = "/opt/cni/bin"
# conf_dir = "/etc/cni/net.d/constellation"
# debug    = false

[pawns.{{.PawnName}}]
cpu    = "100%"
memory = "512M"

[pawns.{{.PawnName}}.labels]
"kubernetes.io/os"   = "linux"
"kubernetes.io/arch" = "amd64"

[pawns.{{.PawnName}}.taints]
"node.periapsis.io/type" = "pawn:NoSchedule"
`

// generateConfig writes a default perigeos.toml to {configDir}/perigeos.toml.
// If the file already exists it is left unchanged to preserve user edits.
func generateConfig(opts *Options, primary bool, logger *slog.Logger) (string, error) {
	configPath := filepath.Join(opts.ConfigDir, "perigeos.toml")

	if _, err := os.Stat(configPath); err == nil {
		logger.Info("Config already exists — skipping generation", "path", configPath)
		return configPath, nil
	}

	hostname, err := os.Hostname()
	if err != nil || hostname == "" {
		hostname = "pawn-01"
	}
	// Use a safe pawn name derived from the hostname.
	pawnName := sanitizePawnName(hostname)

	tmpl, err := template.New("config").Parse(defaultConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("parse config template: %w", err)
	}

	data := struct {
		Primary  bool
		PawnName string
	}{
		Primary:  primary,
		PawnName: pawnName,
	}

	f, err := os.OpenFile(configPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o640)
	if err != nil {
		return "", fmt.Errorf("create config file %s: %w", configPath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("render config template: %w", err)
	}

	logger.Info("Default config written", "path", configPath, "pawn", pawnName, "primary", primary)
	return configPath, nil
}

// sanitizePawnName converts a hostname into a valid pawn name.
// It lowercases, replaces underscores/dots with hyphens, and trims.
func sanitizePawnName(name string) string {
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, "_", "-")
	name = strings.ReplaceAll(name, ".", "-")
	name = strings.Trim(name, "-")
	if name == "" {
		return "pawn-01"
	}
	return name
}
