version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - gosec

linters-settings:
  lll:
    line-length: 200
  gosec:
    excludes:
      - G304

issues:
  exclude-use-default: false
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). (is not checked|Errors unhandled)

run:
  exclude-dirs:
    - internal/kubernetes
    - internal/podutils
