import http from "k6/http"
import { check, sleep } from "k6"
import { Rate } from "k6/metrics"

// Custom metrics
const errorRate = new Rate("errors")
//const podDistribution = new Trend("unique_pods_seen")

// Target: ClusterIP service (override with -e TARGET=...)
const TARGET = __ENV.TARGET || "http://10.43.48.129"

export const options = {
  scenarios: {
    // Ramp: gentle start -> full load -> sustained -> cool down
    ramp: {
      executor: "ramping-vus",
      startVUs: 0,
      stages: [
        { duration: "15s", target: 100 },
        { duration: "30s", target: 500 },
        { duration: "60s", target: 500 },
        { duration: "30s", target: 1000 },
        { duration: "60s", target: 1000 },
        { duration: "15s", target: 0 },
      ],
    },
  },
  thresholds: {
    http_req_duration: ["p(95)<500", "p(99)<1000"],
    errors: ["rate<0.01"],
  },
}

export default function () {
  const res = http.get(TARGET)

  // 1. Base Checks
  const ok = check(res, {
    "status 200": (r) => r.status === 200,
    "has body": (r) => r.body && r.body.length > 0,
    "has perigeos": (r) => r.body && r.body.includes("perigeos"),
  })

  errorRate.add(!ok)

  // 2. Extract Pawn (NODE_NAME) and track statistics
  if (res.status === 200 && res.body) {
    // Regex looks exactly for the HTML structure generated by your page.sh script
    const match = res.body.match(/<span class="label">pawn<\/span><span class="value">([^<]+)<\/span>/)

    if (match && match.length > 1) {
      const pawnName = match[1] // e.g., "worker-node-1"

      // We create a dynamic check name.
      // k6 will automatically count and print these in the final console summary
      const dynamicCheckObj = {}
      dynamicCheckObj[`pawn responded: ${pawnName}`] = (r) => true
      check(res, dynamicCheckObj)

    } else {
      check(res, { "pawn responded: UNKNOWN": (r) => true })
    }
  }

  sleep(0.05)
}
