---
apiVersion: v1
kind: Pod
metadata:
  name: oom-pod

spec:
  containers:
    - name: oom-container
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "256M"]
      resources:
        limits:
          memory: "64Mi"
