---
apiVersion: v1
kind: Pod
metadata:
  name: init-crash-pod

spec:
  initContainers:
    - name: init-fail-container
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo 'Init container: Checking database...'; sleep 5; echo 'DB not
            found! Crashing...'; exit 1",
        ]

  containers:
    - name: main-app-container
      image: busybox
      command: ["sh", "-c", "echo 'I am the main app!'; sleep 3600"]
