apiVersion: v1
kind: Pod
metadata:
  name: security-test
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: compute-00
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - name: test
    image: docker.io/library/alpine:latest
    command: ["/bin/sh", "-c", "echo uid=$(id -u) gid=$(id -g); cat /proc/self/uid_map; sleep 300"]
  tolerations:
  - operator: Exists
