---
apiVersion: v1
kind: Pod
metadata:
  name: multi-test
  namespace: default

spec:
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: compute-00

  containers:
  - name: short
    image: docker.io/library/alpine:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "echo short starting; sleep 3; echo short done; exit 1"]

  - name: long
    image: docker.io/library/alpine:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "echo long starting; sleep 30; echo long done"]

  tolerations:
  - operator: Exists
